# Generated by Django 3.2.7 on 2021-09-04 14:46

from django.db import migrations, models
import store_project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=store_project.utils.image_path_generator, verbose_name='product images'),
        ),
    ]
